/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as MarketIntelligenceRouteImport } from './routes/market-intelligence'
import { Route as RecommendationsRouteImport } from './routes/recommendations'
import { Route as VesselFeasibilityRouteImport } from './routes/vessel-feasibility'
import { Route as VoyagePlannerRouteImport } from './routes/voyage-planner'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketIntelligenceRoute = MarketIntelligenceRouteImport.update({
  id: '/market-intelligence',
  path: '/market-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const RecommendationsRoute = RecommendationsRouteImport.update({
  id: '/recommendations',
  path: '/recommendations',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselFeasibilityRoute = VesselFeasibilityRouteImport.update({
  id: '/vessel-feasibility',
  path: '/vessel-feasibility',
  getParentRoute: () => rootRouteImport,
} as any)
const VoyagePlannerRoute = VoyagePlannerRouteImport.update({
  id: '/voyage-planner',
  path: '/voyage-planner',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/vessel-feasibility': typeof VesselFeasibilityRoute
  '/voyage-planner': typeof VoyagePlannerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/vessel-feasibility': typeof VesselFeasibilityRoute
  '/voyage-planner': typeof VoyagePlannerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forecast': typeof ForecastRoute
  '/market-intelligence': typeof MarketIntelligenceRoute
  '/recommendations': typeof RecommendationsRoute
  '/vessel-feasibility': typeof VesselFeasibilityRoute
  '/voyage-planner': typeof VoyagePlannerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forecast'
    | '/market-intelligence'
    | '/recommendations'
    | '/vessel-feasibility'
    | '/voyage-planner'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forecast'
    | '/market-intelligence'
    | '/recommendations'
    | '/vessel-feasibility'
    | '/voyage-planner'
  id:
    | '__root__'
    | '/'
    | '/forecast'
    | '/market-intelligence'
    | '/recommendations'
    | '/vessel-feasibility'
    | '/voyage-planner'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForecastRoute: typeof ForecastRoute
  MarketIntelligenceRoute: typeof MarketIntelligenceRoute
  RecommendationsRoute: typeof RecommendationsRoute
  VesselFeasibilityRoute: typeof VesselFeasibilityRoute
  VoyagePlannerRoute: typeof VoyagePlannerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market-intelligence': {
      id: '/market-intelligence'
      path: '/market-intelligence'
      fullPath: '/market-intelligence'
      preLoaderRoute: typeof MarketIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recommendations': {
      id: '/recommendations'
      path: '/recommendations'
      fullPath: '/recommendations'
      preLoaderRoute: typeof RecommendationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessel-feasibility': {
      id: '/vessel-feasibility'
      path: '/vessel-feasibility'
      fullPath: '/vessel-feasibility'
      preLoaderRoute: typeof VesselFeasibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voyage-planner': {
      id: '/voyage-planner'
      path: '/voyage-planner'
      fullPath: '/voyage-planner'
      preLoaderRoute: typeof VoyagePlannerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForecastRoute: ForecastRoute,
  MarketIntelligenceRoute: MarketIntelligenceRoute,
  RecommendationsRoute: RecommendationsRoute,
  VesselFeasibilityRoute: VesselFeasibilityRoute,
  VoyagePlannerRoute: VoyagePlannerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
